site_name: pinklure's posts
site_url: https://pinklure.github.io
site_author: pinklure
site_description: pinklure's Individual Posts Site

copyright: Copyright &copy; 2022-present <a href="https://github.com/pinklure" target="_blank" rel="noopener noreferrer">pinklure</a>

theme:
  name: material
  language: zh
  logo: images/avatar.png
  favicon: images/avatar.png
  include_search_page: false
  search_index_only: false

  palette:
    scheme: default
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.sticky
    - navigation.sections
    - navigation.expand
    # - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.intergrate
    - search.suggest
    - search.highlight
    - header.autohide
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pinklure
      name: pinklure on Github
  extra:
    generator: true

plugins:
  - search:
      lang:
        - en
        - ja
  - glightbox


markdown_extensions:
  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
      toc_depth: 6
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Posts:
    - posts/index.md
    - Linux:
        - posts/linux/index.md
        - Performance Observability:
          - posts/linux/performance_observability/index.md
          - dmesg: posts/linux/performance_observability/dmesg.md
          - ps: posts/linux/performance_observability/ps.md
          - top: posts/linux/performance_observability/top.md
          - vmstat: posts/linux/performance_observability/vmstat.md
  - Archive:
    - archive/index.md

